name: Backup Repository

on:
  schedule:
    - cron: '0 5 * * *'

  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  call-shared-backup-repo-workflow:
    uses: plantemoran-appdev/shared-github-workflows/.github/workflows/shared--backup-repo.yml@develop
