name: Pull Request Auto Assignment

on:
  workflow_call:
    secrets:
      additional-access-pat:
        description: The PAT that will be used for additional access
        required: true

jobs:
  pull-request-assignment:
    name: Pull Request Auto Assignment
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request Auto Assignment
        uses: plantemoran-appdev/gh-action-pr-auto-assign@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          additionalAccessPat: ${{ secrets.additional-access-pat }}
