# since we're using vercel/ncc to package up our custom actions (so we don't have to commit node_modules)
# we need to ensure that the built (dist/) files have been created/updated properly

name: Validate Built (dist/) Files for Custom Action

on:
  workflow_call:

jobs:
  validate-built-files:
    name: Validate built (dist/) files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install dependencies
        run: npm ci

      - name: Rebuild the action
        run: npm run build-action

      - name: Compare the expected and actual index.js files
        id: diff-built-files
        run: |
          if [ "$(git diff --ignore-all-space dist/index.js | wc -l)" -gt "0" ]; then
            echo "Updated built (dist/) files have not been committed. See status below:"
            git diff --ignore-all-space dist/index.js
            exit 1
          fi

      # if diff-built-files failed, upload the expected diff/ as an artifact
      - name: Upload expected dist/ files
        uses: actions/upload-artifact@v2
        if: ${{ failure() && steps.diff-built-files.conclusion == 'failure' }}
        with:
          name: dist
          path: dist/
